version: '3'

services:
  connect-documentation:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080'
    volumes:
      - '${APP_VOLUME}'
    environment:
      TZ: ${TZ-Europe/Amsterdam}
    networks:
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.connect.tls=true'
      - 'traefik.http.routers.connect.entrypoints=https'
      - 'traefik.http.routers.connect.rule=Host(`connect.myofflinestore.com`)'

networks:
  default:
    external:
      name: gateway
