name: Test

on: push

jobs:
    deploy:
        name: Test

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: actions/setup-node@v4

            -   name: Test
                run: |
                    npm install
                    npm run test
                    npm run build
