name: Test

on: push

jobs:
    deploy:
        name: Test

        runs-on: ubuntu-20.04

        steps:
            -   uses: actions/checkout@v2

            -   uses: actions/setup-node@v1
                with:
                    node-version: 15.x

            -   name: Test
                run: |
                    npm install
                    npm run test
                    npm run build
